# Habilitar o console H2
spring.h2.console.path=/h2-console
  # Configurações do Banco de Dados
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
  # Criar/atualizar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
```properties
    # Configurações adicionais do H2
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=false
spring.main.allow-bean-definition-overriding=true
# AppSec: Use uma chave longa e aleatória (ex: 32+ caracteres)
jwt.secret=ZmFiaW9nYXJjaWFzZWN1cml0eXRlc3RzZW50aW5lbGF1dGgyMDI0YXBwc2Vja
# 1 hora de expiração (em milissegundos)
jwt.expiration=86400000
sessionManagement.SessionCreationPolicy=STATELESS
jwt.refreshExpiration=172800000
